name: Test geometry_tutorials
on:
  pull_request:
  push:
    branches:
      - ros2

jobs:
  build_and_test_source_jazzy:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
    - name: Build and run tests
      id: action-ros-ci
      uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: |
          turtle_tf2_py
          turtle_tf2_cpp
        target-ros2-distro: jazzy
        vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/jazzy/ros2.repos
        colcon-defaults: |
          {
            "build": {
              "cmake-args": [
                "-DCMAKE_CXX_FLAGS=\"-Werror\""
              ]
            },
            "test": {
              "ctest-args": ["-LE", "xfail"],
              "pytest-args": ["-m", "not xfail"]
            }
          }
  build_and_test_binaries_jazzy:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
    - name: Build and run tests
      id: action-ros-ci
      uses: ros-tooling/action-ros-ci@v0.3
      with:
        package-name: |
          turtle_tf2_py
          turtle_tf2_cpp
        target-ros2-distro: jazzy
        colcon-defaults: |
          {
            "build": {
              "cmake-args": [
                "-DCMAKE_CXX_FLAGS=\"-Werror\""
              ]
            },
            "test": {
              "ctest-args": ["-LE", "xfail"],
              "pytest-args": ["-m", "not xfail"]
            }
          }
